import {
  Archive,
  Banknote,
  BookOpen,
  Boxes,
  Building2,
  CalendarDays,
  Check,
  CheckCircle2,
  ChevronDown,
  ChevronRight,
  CircleAlert,
  ClipboardList,
  Clock,
  CloudOff,
  Copy,
  Drama,
  ExternalLink,
  Eye,
  File,
  FileQuestion,
  FileText,
  Film,
  Filter,
  Folder,
  FolderOpen,
  Gavel,
  Grid3x3,
  Hammer,
  History,
  Download,
  ImageIcon,
  Info,
  LayoutDashboard,
  Link2,
  List,
  Lock,
  LogOut,
  Mail,
  Megaphone,
  Mic,
  Music,
  Palette,
  Pencil,
  Pin,
  PinOff,
  Plus,
  Presentation,
  RefreshCw,
  Search,
  Settings,
  Sheet,
  ShieldCheck,
  Shirt,
  Sparkles,
  Star,
  Tag,
  Theater,
  Ticket,
  Trash2,
  TriangleAlert,
  UploadCloud,
  UserCog,
  UserPlus,
  Users,
  Wrench,
  X,
  type LucideIcon,
} from "lucide-react";

/**
 * Icon keys are stored in the database (Category.icon), so this map is the
 * contract: add to it rather than renaming keys.
 */
export const ICONS: Record<string, LucideIcon> = {
  archive: Archive,
  budget: Banknote,
  building: Building2,
  calendar: CalendarDays,
  check: Check,
  "check-circle": CheckCircle2,
  "chevron-down": ChevronDown,
  "chevron-right": ChevronRight,
  clipboard: ClipboardList,
  clock: Clock,
  cloud_off: CloudOff,
  copy: Copy,
  costume: Shirt,
  dashboard: LayoutDashboard,
  doc: FileText,
  external: ExternalLink,
  eye: Eye,
  file: File,
  film: Film,
  filter: Filter,
  folder: Folder,
  "folder-open": FolderOpen,
  form: FileQuestion,
  gavel: Gavel,
  grid: Grid3x3,
  history: History,
  download: Download,
  image: ImageIcon,
  info: Info,
  link: Link2,
  list: List,
  lock: Lock,
  logout: LogOut,
  mail: Mail,
  marketing: Megaphone,
  mic: Mic,
  music: Music,
  palette: Palette,
  pdf: File,
  pencil: Pencil,
  pin: Pin,
  "pin-off": PinOff,
  plus: Plus,
  props: Boxes,
  refresh: RefreshCw,
  script: BookOpen,
  search: Search,
  settings: Settings,
  sheet: Sheet,
  shield: ShieldCheck,
  slides: Presentation,
  sparkles: Sparkles,
  star: Star,
  tag: Tag,
  theater: Drama,
  ticket: Ticket,
  tools: Hammer,
  trash: Trash2,
  upload: UploadCloud,
  "user-cog": UserCog,
  users: Users,
  "user-plus": UserPlus,
  venue: Theater,
  warning: TriangleAlert,
  alert: CircleAlert,
  wrench: Wrench,
  x: X,
};

/** Every icon a category can pick, in the order shown in the admin picker. */
export const CATEGORY_ICON_KEYS = [
  "folder",
  "budget",
  "calendar",
  "clipboard",
  "users",
  "script",
  "palette",
  "costume",
  "props",
  "tools",
  "marketing",
  "ticket",
  "gavel",
  "venue",
  "building",
  "mic",
  "music",
  "film",
  "mail",
  "archive",
  "sparkles",
  "star",
  "shield",
] as const;

export function Icon({
  name,
  className,
  strokeWidth = 1.75,
  title,
}: {
  name: string;
  className?: string;
  strokeWidth?: number;
  title?: string;
}) {
  const Component = ICONS[name] ?? Folder;
  return (
    <Component
      className={className}
      strokeWidth={strokeWidth}
      aria-hidden={title ? undefined : true}
      aria-label={title}
    >
      {title ? <title>{title}</title> : null}
    </Component>
  );
}
